# Generated by Django 3.2.25 on 2024-09-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkifi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=155)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=155)),
                ('password', models.CharField(max_length=155)),
                ('repeatpassword', models.CharField(max_length=155)),
                ('date', models.DateField()),
            ],
        ),
    ]
