# Generated by Django 3.2.25 on 2024-09-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkifi_app', '0003_loginusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('textarea', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
