# Generated by Django 3.2.25 on 2024-09-25 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkifi_app', '0011_setting_settingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderurl', models.CharField(max_length=200)),
                ('ordertitle', models.CharField(max_length=500)),
                ('orderprice', models.IntegerField()),
                ('ordercurrency', models.CharField(max_length=500)),
                ('orderfirstname', models.CharField(max_length=200)),
                ('orderlastname', models.CharField(max_length=500)),
                ('orderemail', models.EmailField(max_length=254)),
                ('orderphone', models.CharField(max_length=500)),
                ('orderaddress', models.CharField(max_length=200)),
                ('ordercity', models.CharField(max_length=500)),
                ('cashdelivery', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Urladmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameadmin', models.CharField(max_length=200)),
                ('urladmin', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
