# Generated by Django 3.2.25 on 2024-09-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkifi_app', '0013_homeemail_profile_settingform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpage',
            name='user',
        ),
    ]
