# Generated by Django 3.2.25 on 2024-09-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkifi_app', '0014_remove_adminpage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urladmin',
            name='user',
        ),
    ]
