# Generated by Django 3.2.25 on 2024-09-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkifi_app', '0015_remove_urladmin_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginusername',
            old_name='loginusername',
            new_name='loginusernameoneg',
        ),
    ]
