# Generated by Django 3.2.25 on 2024-09-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkifi_app', '0016_rename_loginusername_loginusername_loginusernameoneg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='user',
        ),
    ]
