from django.contrib import admin
from django.urls import path,include
from linkifi_app import views
urlpatterns = [
    path('', views.home , name = 'home.html'),
    path('login/' , views.loginuser , name = 'login'),
    path('signup/' , views.signup , name = 'signup'),
    path('logout/' , views.logoutuser , name = 'logout'),
    path('pricing/' , views.pricing , name = 'pricing'),
    path('Feature/' , views.Feature , name = 'Feature'),
    path('About/' , views.About , name = 'About'),
    path('loginusername/' , views.loginusername , name = 'loginusername'),
    path('Select_plan/' , views.Select_plan , name = 'Select_plan'),
    path('contact/' , views.contact , name = 'contact'),
    path('billing_pro/' , views.billing_pro , name = 'billing_pro'),
    path('billing_enterprise/' , views.billing_enterprise , name = 'billing_enterprise'),
    path('select_template/' , views.select_template , name = 'select_template'),
    path('select_type/' , views.select_type , name = 'select_type'),
    path('select_platform/' , views.select_platform , name = 'select_platform'),
    path('Add_links/' , views.Add_links , name = 'Add_links'),
    path('Add_profile/' , views.Add_profile , name = 'Add_profile'),
    path('profile_success/' , views.profile_success , name = 'profile_success'),
    path('adminpage/' , views.adminpage , name = 'adminpage'),
    path('shop/' , views.shop , name = 'shop'),
    path('appearance/' , views.appearance , name = 'appearance'),
    path('analytics/' , views.analytics , name = 'analytics'),
    path('setting/' , views.setting , name = 'setting'),
    path('shopproduct/' , views.shopproduct , name = 'shopproduct'),
    path('showallproduct/' , views.showallproduct , name = 'showallproduct'),
    path('delete-product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('shopsetting', views.shopsetting, name='shopsetting'), 
    path('orderproduct', views.orderproduct, name='orderproduct'), 
    path('shop_plus', views.shop_plus, name='shop_plus'), 
    path('helpcenter/', views.helpcenter, name='helpcenter'),
    path('privacy/', views.privacy, name='privacy'), 
    path('faqs/', views.faqs, name='faqs'), 
    path('check-username/<str:username>/', views.check_username, name='check_username'),
    path('Linkifi.ee/<str:username>/', views.user_page, name='user_page'),
] 
